### PR TITLE
Lazy builders

### PR DESCRIPTION
**Pull request by starsfordummies**
since we end up writing those a million times in testing, these shorthands might be useful
for me we could also export them

### CODE REVIEW

**Comment by mofeing** [comment]
I like the idea of having these kind of constructors, but not this way nor with these names. We can write another proposal when I'm back.

**Comment by starsfordummies** [comment]
ok, note that at the moment these are mostly meant to make life easier on us poor testers, so the more straightforward the better

**Comment by starsfordummies** [comment]
With latest changes and all this is outdated, besides now it's relatively easy to build an MPS with rand()

**Comment by mofeing** [comment]
We can still add a constructor for Pauli strings like `Product("001+")` if you want

**Pull request closed without merging**
